# Generated by Django 3.2.9 on 2021-11-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Caps', 'Caps'), ('Hats', 'Hats'), ('Backpacks', 'Backpacks'), ('T-shirts', 'T-shirts'), ('Uniforms', 'Uniforms')], max_length=20, verbose_name='Product type')),
                ('subtype', models.CharField(blank=True, choices=[('Low', 'Low Crown'), ('Med', 'Med Crown'), ('High', 'High Crown')], max_length=20, verbose_name='Sub type')),
                ('sizesAvailable', models.CharField(blank=True, max_length=30)),
                ('smallMediumQuantity', models.IntegerField(default=0)),
                ('largeExtraLargeQuantity', models.IntegerField(default=0)),
                ('universalQuantity', models.IntegerField(default=0)),
                ('youthQuantity', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('price', models.IntegerField()),
                ('manufacturer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.manufacturer')),
                ('model', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.model')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('isMainPicture', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
    ]
